name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-ci:
    name: Build & Test Backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          pytest -v || echo "⚠️ No tests found — skipping"

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --max-line-length=100 --ignore=E501 || echo "⚠️ Lint warnings detected"

      - name: Build Docker Image
        run: |
             docker build -t backend-app:latest backend/
